pipeline {
    agent any
    stages {
        stage('importing git repo') {
            steps {
                git branch: 'main', url: 'https://github.com/BhushanGit04096/devops-projects'
            }
        }
        stage('CD to directory and build') {
            steps {
                dir('jenkins-projects/python-jenkins-docker-app ') {
                    sh 'python3 app.py'
                }
            }
        }
        stage('CD to directory and test') {
            steps {
                dir('jenkins-projects/python-jenkins-docker-app ') {
                    sh 'python3 -m unittest discover "tests "'
                }
            }
        }
    }
}
