pipeline {
    agent any
    stages {
        stage('importing git repo') {
            steps {
                git branch: 'main', url: 'https://github.com/BhushanGit04096/devops-projects'
            }
        }
        stage('CD to directory and build') {
            steps {
                dir('jenkins-projects/python-jenkins-docker-app ') {
                    sh 'python3 app.py'
                }
            }
        }
        stage('CD to directory and test') {
            steps {
                dir('jenkins-projects/python-jenkins-docker-app ') {
                    sh 'python3 -m unittest discover "tests "'
                }
            }
        }
         stage('CD to directory and docker build') {
            steps {
                dir('jenkins-projects/python-jenkins-docker-app ') {
                    sh 'docker build -t python-app:latest .'
                }
            }
        }
        stage('Docker Run') {
            steps {
                dir('jenkins-projects/python-jenkins-docker-app ') {
                    sh 'docker run --rm python-app:latest'
                }
            }
        } 
        stage('Docker tag and push') {
            steps {
                dir('jenkins-projects/python-jenkins-docker-app') {
                  withCredentials([usernamePassword(credentialsId: 'bhushan0496', passwordVariable: 'password', usernameVariable: 'dockeruser')]) {
                 sh '''
                            echo "$password" | docker login -u "$dockeruser" --password-stdin
                            docker tag python-app:latest bhushan0496/python-app:latest
                            docker push bhushan0496/python-app:latest
                        '''
}
                }
            }
        } 
    }
}
